name: Validate text data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tier-ii-text-validation:
    runs-on: ubuntu-latest

    steps:
    - run: echo "checking out repo"
    - name: Checkout repository
      uses: actions/checkout@v4

    - run: echo "setting up Python"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

#     - run: echo "installing Python dependencies"
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

    - run: echo "setting execute permission for validation script"
    - name: Set execute permission for validation script
      run: chmod +x .github/scripts/validate_tier_ii_text_data.sh

    - run: echo "running Tier II validation script"
    - name: Run script
      run: .github/scripts/validate_tier_ii_text_data.sh
